// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-h7rEZIwKGPYVDeElisAvgEH6aBpxrcM',
    appId: '1:854968345129:web:1f414cee84650343703238',
    messagingSenderId: '854968345129',
    projectId: 'quipster-628a0',
    authDomain: 'quipster-628a0.firebaseapp.com',
    storageBucket: 'quipster-628a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_pLt9KuSmFJHqOhNA6VctPSo4UW_5gfg',
    appId: '1:854968345129:android:eb347d0d79ddfffc703238',
    messagingSenderId: '854968345129',
    projectId: 'quipster-628a0',
    storageBucket: 'quipster-628a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTyx-226v-YkLKhgCJFCqVlEdAyZ8bV0',
    appId: '1:854968345129:ios:805640f60b3d5713703238',
    messagingSenderId: '854968345129',
    projectId: 'quipster-628a0',
    storageBucket: 'quipster-628a0.appspot.com',
    iosClientId: '854968345129-vv85hoa1user6nc8mlvn878mpfm0t766.apps.googleusercontent.com',
    iosBundleId: 'com.example.quipster',
  );

}